Added the new changes shown as completed in the ToDo list.

diff --git a/ARdump b/ARdump
--- a/ARdump
+++ b/ARdump
@@ -1,15 +1,14 @@
 #!/bin/bash
-# Quick n' dirty file transfer utility for professional film/TV DIT workflows
+# Quick 'n dirty file transfer utility for professional film/TV DIT workflows
 # By Alex Fichera and Rio Velarde, 2016
-# version=1.0.5 - Windows
+# Dependencies: rsync, md5deep, email
+
+version=1.0.8 # - Windows
+
 src=$1/
 dest=$2
 mail=$3
 date=$(date)
-finalDest=$dest/$(basename $src)
-logName=$(basename $dest)
-# logName+=".$date"
-logDest=$dest/${logName}_LOGS
 
 IFS="$(printf '\n\t')"
 # Remove SPACE, so filenames with spaces work well.
@@ -24,50 +23,74 @@ for file in ./* ; do # Use "./*" ... NEVER bare "*" ...
 	fi
 done
 
+thePath=$(basename $src)
+thePath+=":"
+
+finalDest=$dest/$(basename $src)
+logName=$(basename $dest)
+# logName+=".$date"
+logDest=$dest/${logName}_LOGS
+
 function make_dump() {
-	#The checksum file requires md5deep. Install from homebrew.
 	mkdir -p $dest
 	mkdir -p $logDest #make required directories if they don't exist
 	
+	echo '' | label $thePath > $logDest/path.txt
+	name="$(sed -n -e 's/^.*is //p;q;' $logDest/path.txt)"
+	rm $logDest/path.txt
+	
 	echo "This transfer is from $src to $dest" >> $logDest/${logName}_COPY_LOG.txt
 	echo "It is starting at" $(date) >> $logDest/${logName}_COPY_LOG.txt
-	echo "**************************************************************************************************" >> $logDest/${logName}_COPY_LOG.txt
+	echo "↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓" >> $logDest/${logName}_COPY_LOG.txt
 	
-	rsync -prtWvi --stats --partial --no-i-r --progress --log-file=$logDest/templog.txt --log-file-format="%C %n" $src $dest/$(basename $dest)
+	rsync -prtWvi --stats --partial --no-i-r --progress --log-file=$logDest/templog.txt --log-file-format="%C %n" $src $dest/$name
+	
+	if [ "$?" -ne "0" ]; then
+		echo "Error: Rsync did not complete execution properly!"
+		echo "RSYNC DID NOT COMPLETE PROPERLY!!!" >> $logDest/${logName}_ERROR_LOG_$date.txt
+		exit 1
+	fi
+	
 	sed 's/^.*] //' $logDest/templog.txt >> $logDest/${logName}_COPY_LOG.txt
-	rm $logDest/templog.txt
 	
 	echo "" >> $logDest/${logName}_COPY_LOG.txt
 	echo "**************************************************************************************************" >> $logDest/${logName}_COPY_LOG.txt
 	echo "The transfer finished at" $(date) >> $logDest/${logName}_COPY_LOG.txt
+	echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^" >> $logDest/${logName}_COPY_LOG.txt
+	echo "" >> $logDest/${logName}_COPY_LOG.txt
 	
 	if [[ $mail != "" ]] ; then
 		echo "The transfer from $src to $dest is complete. Now beginning checksum..." | cat - $logDest/COPY_LOG.txt | email -s "ARdump TRANSFER IS COMPLETE!" $mail
 	fi
 	
-	echo "THIS LOG IS CURRENTLY NOT VALID AS THE CHECKSUM HAS NOT COMPLETED!!!!!" >> $logDest/${logName}_ERROR_LOG.txt
+	echo "THIS LOG IS CURRENTLY NOT VALID AS THE CHECKSUM HAS NOT COMPLETED!!!!!" >> $logDest/${logName}_ERROR_LOG_$date.txt
 	
-	echo "This error log is for the copy from $src to $dest" >> $logDest/${logName}_ERROR_LOG.txt
-	echo "Error checking began on" $(date) >> $logDest/${logName}_ERROR_LOG.txt
+	echo "This error log is for the copy from $src to $dest" >> $logDest/${logName}_ERROR_LOG_$date.txt
+	echo "Error checking began on" $(date) >> $logDest/${logName}_ERROR_LOG_$date.txt
 
-	echo "**************************************************************************************************" >> $logDest/${logName}_ERROR_LOG.txt
-	echo "THIS SECTION SHOWS ERRORS (IF ANY) FROM THE RSYNC TRANSFER" >> $logDest/${logName}_ERROR_LOG.txt
-	echo "**************************************************************************************************" >> $logDest/${logName}_ERROR_LOG.txt
-	grep -i -n "WARNING" $logDest/${logName}_COPY_LOG.txt >> $logDest/${logName}_ERROR_LOG.txt
-	grep -i -n "ERROR" $logDest/${logName}_COPY_LOG.txt >> $logDest/${logName}_ERROR_LOG.txt
+	echo "**************************************************************************************************" >> $logDest/${logName}_ERROR_LOG_$date.txt
+	echo "THIS SECTION SHOWS ERRORS (IF ANY) FROM THE RSYNC TRANSFER" >> $logDest/${logName}_ERROR_LOG_$date.txt
+	echo "**************************************************************************************************" >> $logDest/${logName}_ERROR_LOG_$date.txt
+	grep -i -n "WARNING" $logDest/templog.txt >> $logDest/${logName}_ERROR_LOG_$date.txt
+	grep -i -n "ERROR" $logDest/templog.txt >> $logDest/${logName}_ERROR_LOG_$date.txt
+	rm $logDest/templog.txt
+	echo "" >> $logDest/${logName}_ERROR_LOG_$date.txt
+	echo "**************************************************************************************************" >> $logDest/${logName}_ERROR_LOG_$date.txt
+	echo "THIS SECTION IS ONLY USED TO SHOW FILES THAT **FAILED** THE HASH CHECK AND MAY NOT HAVE COPIED CORRECTLY" >> $logDest/${logName}_ERROR_LOG_$date.txt
+	echo "**************************************************************************************************" >> $logDest/${logName}_ERROR_LOG_$date.txt
 	
-	echo "" >> $logDest/${logName}_ERROR_LOG.txt
-	echo "**************************************************************************************************" >> $logDest/${logName}_ERROR_LOG.txt
-	echo "THIS SECTION IS ONLY USED TO SHOW FILES THAT **FAILED** THE HASH CHECK AND MAY NOT HAVE COPIED CORRECTLY" >> $logDest/${logName}_ERROR_LOG.txt
-	echo "**************************************************************************************************" >> $logDest/${logName}_ERROR_LOG.txt
+	md5deep -e -r -n -m $logDest/${logName}_COPY_LOG.txt $dest >> $logDest/${logName}_ERROR_LOG_$date.txt
 	
-	md5deep -e -r -n -s -m $logDest/${logName}_COPY_LOG.txt $dest >> $logDest/${logName}_ERROR_LOG.txt
+	if [ "$?" -ne "0" ]; then
+		echo "Warning: MD5Deep did not exit clean!"
+		echo "WARNING: MD5Deep did not exit clean!!!" >> $logDest/${logName}_ERROR_LOG_$date.txt
+	fi
 
-	echo "" >> $logDest/${logName}_ERROR_LOG.txt
-	echo "**************************************************************************************************" >> $logDest/${logName}_ERROR_LOG.txt
-	echo "Checksum verification complete." $(date) >> $logDest/${logName}_ERROR_LOG.txt
+	echo "" >> $logDest/${logName}_ERROR_LOG_$date.txt
+	echo "**************************************************************************************************" >> $logDest/${logName}_ERROR_LOG_$date.txt
+	echo "Checksum verification complete." $(date) >> $logDest/${logName}_ERROR_LOG_$date.txt
 	
-	tail -n +2 $logDest/${logName}_ERROR_LOG.txt > $logDest/FILE.tmp && mv $logDest/FILE.tmp $logDest/${logName}_ERROR_LOG.txt
+	tail -n +2 $logDest/${logName}_ERROR_LOG_$date.txt > $logDest/FILE.tmp && mv $logDest/FILE.tmp $logDest/${logName}_ERROR_LOG_$date.txt
 	
 	if [[ $mail != "" ]] ; then
 		echo "The verfication of the $src to $dest transfer is complete!" | cat - $logDest/ERROR_LOG.txt | email -s "ARdump VERIFICATION IS COMPLETE!" $mail
